imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: sonata.yml }
    - { resource: media.yml }

parameters:
    aulalopati.mail: 'aula@lopati.cat'

# Framework
framework:
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: [ "twig"] }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "SonataCoreBundle:Form:datepicker.html.twig"
    globals:
        google_analytics_enabled: "%google_analytics_enabled%"
        google_analytics_account: "%google_analytics_account%"
        project_title:            "%project_title%"
        admin_tag_version:        "1.0.02"

# Assetic
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        cssrewrite: ~

# Doctrine
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# FOS User
fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     AulaLoPati\UserBundle\Entity\User
    group:
        group_class:   AulaLoPati\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

# TinyMCE Bundle
stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: ".tinymce"
    language: "%locale%"
    theme:
        # simple: ~
        simple:   # original theme "advanced"
            plugins:
                - "advlist autolink lists link charmap print preview hr anchor pagebreak"
                - "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "insertdatetime nonbreaking save contextmenu directionality"
                - "emoticons template paste textcolor"
            toolbar1: "undo redo | styleselect | bold italic underline | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link | print preview"
            image_advtab: true
            templates:
                - {title: 'Test template 1', content: 'Test 1'}
                - {title: 'Test template 2', content: 'Test 2'}
        # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
        bbcode:
            plugins: ["bbcode, code, link, preview"]
            menubar: false
            toolbar1: "bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code,preview"
