# Sonata Admin
sonata_admin:
    title:      "%project_title%"
    title_logo: "/images/logo_lopati_inverted.png"
    persist_filters: true
    options:
        html5_validate: true
        confirm_exit:   true
        use_select2:    true
        pager_links:    10
    templates:
        layout: "BlogBundle:Admin:my_standard_layout.html.twig"
    dashboard:
        groups:
            Presentacio:
            Jornades:
            Projectes:
            Convocatories:
            Recursos:

# Sonata Block
sonata_block:
    default_contexts: [ admin ]
    blocks:
        sonata.user.block.menu:
        sonata.user.block.account:
        sonata.admin.block.admin_list:
        sonata.block.service.text:

# Sonata User
sonata_user:
    security_acl: false
    manager_type: orm
