# Sonata Admin
sonata_admin:
  title:  "Administrador de l'Aula al Pati"
  title_logo: /images/logo_lopati_inverted.png
  templates:
    layout: BlogBundle:Admin:my_standard_layout.html.twig
    dashboard: SonataAdminBundle:Core:dashboard.html.twig
    ajax: SonataAdminBundle::ajax_layout.html.twig
    list: SonataAdminBundle:CRUD:list.html.twig
    show: SonataAdminBundle:CRUD:show.html.twig
    edit: SonataAdminBundle:CRUD:edit.html.twig
  dashboard:
    groups:
      Presentació:
      Jornades:
      Projectes:
      Convocatòries:
      Recursos:

# Sonata Block
sonata_block:
    default_contexts: [ admin ]
    blocks:
        sonata.user.block.menu:
        sonata.user.block.account:
        sonata.admin.block.admin_list:
        sonata.block.service.text:

# Sonata User
sonata_user:
    security_acl: false
    manager_type: orm

# Sonata FOS User Bundle
#sonata_user:
#    security_acl: true
#    class:                  # Entity Classes
#        user:               Application\Sonata\UserBundle\Entity\User
#        group:              Application\Sonata\UserBundle\Entity\Group
#    admin:                  # Admin Classes
#        user:
#            class:          Sonata\UserBundle\Admin\Entity\UserAdmin
#            controller:     SonataAdminBundle:CRUD
#            translation:    SonataUserBundle
#        group:
#            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
#            controller:     SonataAdminBundle:CRUD
#            translation:    SonataUserBundle
#
# FOS User Bundle
#fos_user:
#    db_driver:      orm # can be orm or odm
#    firewall_name:  main
#    user_class:     Application\Sonata\UserBundle\Entity\User
#    group:
#        group_class: Application\Sonata\UserBundle\Entity\Group
