services:

        
  sonata.aulalopati.admin.pagina:
    class: AulaLoPati\BlogBundle\Admin\JornadaAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'Jornades', label: jornada }
    arguments:
      - null
      - AulaLoPati\BlogBundle\Entity\Jornada
      - BlogBundle:Admin
  

      

      
 
